url: https://hilworkshops.github.io
baseurl: /hil-dc2022/

# Site settings
title: HIL-DC2022
email: j.yang-3@tudelft.nl
description: "Human-In-the-Loop Data Curation Workshop 2022"


# Team names, titles and social links
people:
- name: Gianluca Demartini
  pic: 1
  position: The University of Queensland, Australia
  email: g.demartini[at]uq.edu.au

- name: Shazia Sadiq
  pic: 2
  position: The University of Queensland, Australia
  email: s.sadiq[at]]uq.edu.au

- name: Jie Yang
  pic: 3
  position: Delft University of Technology, Netherlands
  email: j.yang-3[at]tudelft.nl


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/search?f=tweets&q=%23hil-dc2022&src=typd
  - title: facebook
    url: https://www.facebook.com/hashtag/hil-dc2022?fref=ts
  

# Postal address (add as many lines as necessary)
address:
  - line: Atlanta
  - line: Georgia, USA

# Build settings
markdown: kramdown
permalink: pretty
