url: https://yangjiera.github.io
baseurl: /citrec2017/

# Site settings
title: CitRec2017
email: j.yang-3@tudelft.nl
description: "ACM RecSys 2017 Workshop: Recommender Systems for Citizens (CitRec2017)."


# Team names, titles and social links
people:
- name: Jie Yang
  pic: 1
  position: Delft University of Technology, Netherlands
  email: j.yang-3[at]tudelft.nl


- name: Zhu Sun
  pic: 2
  position: Nanyang Technological University, Singapore
  email: sunzhu[at]ntu.edu.sg

- name: Alessandro Bozzon
  pic: 3
  position: Delft University of Technology, Netherlands
  email: a.bozzon[at]tudelft.nl

- name: Jie Zhang
  pic: 4
  position: Nanyang Technological University, Singapore
  email: zhangj[at]ntu.edu.sg

- name: Martha Larson
  pic: 5
  position: Radboud University Nijmegen, Netherlands
  email: m.a.larson[at]tudelft.nl

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/search?f=tweets&q=%23citrec2017&src=typd
  - title: facebook
    url: https://www.facebook.com/hashtag/citrec2017?fref=ts
  

# Postal address (add as many lines as necessary)
address:
  - line: Teatro Sociale di Como
  - line: Via Vincenzo Bellini, 3, 22100 Como
  - line: CO, Italy

# Build settings
markdown: kramdown
permalink: pretty
